### ISSUE TITLE
version.php states version 2021052500 is required

### ISSUE THREAD

**Issue by NinaHerrmann** [learnweb/format_progresstopics#1]
This version is in the future.

**Comment by sevenseas-gists** [comment]
absolutely, however if you check the topic format you will see that it requires this version. Since the format is based on the topics format i tought it would be best to make sure it's requirements are satisfied
https://github.com/moodle/moodle/blob/master/course/format/topics/version.php

**Comment by NinaHerrmann** [comment]
Hey Robin, 
yes but if you look at the STABLE_39 Master, you will see that the required version number changes. Please set the version number accordingly and test whether it works with the MOODLE_STABLE_39 branch, so we can deploy it when it is ready ;)
